"""Initial migration.

Revision ID: 05ca303a619f
Revises: 
Create Date: 2021-05-21 23:24:53.144700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ca303a619f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    op.alter_column('user', 'created',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('user', 'confirmed_on')
    op.drop_column('user', 'confirmed')
    op.drop_column('user', 'admin')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('firstname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
